### PR TITLE
Simple DummyLoginProvider

### PR DESCRIPTION
**Pull request by acanewby**
A login provider that simulates a social login without requiring remote network access or application registration with any third party authentication provider.  Allows custom configuration of dummy authenticated user details.

### CODE REVIEW

**Comment by jaibatrik** [comment]
Thanks for your PR. I think I don't have any issue with it except the placement of the documentation in the main README. I think the information needs to go in a different README file, or may be in JSDoc. I cannot think of any place to put the new README file yet, but I'll think of something and update.

Thanks again!

**Comment by acanewby** [comment]
Glad you like it.

Whatever you think best.

Adrian 


---------------------------
Adrian Newby
acanewby@yahoo.com
+1 310 293 2448
+44 7933 573147

**Comment by acanewby** [comment]
If you are still interested in the Dummy provider, I made a fix so it isn't automatically already logged in with the dummy user.  Now, the signIn, signOut, getLoginStatus works as you would expect.

I also merged your recent commits into my fork so the PR should be fairly clean.

Haven't done anything with the README, since you indicated you might want to rearrange that yourself.

Adrian

**Comment by jaibatrik** [comment]
Thanks, I think I am okay with it. I'll merge this after resolving the conflicts.

**Comment by jaibatrik** [comment]
I'll merge this when the newly released v3 becomes stable.

**Comment by jaibatrik** [comment]
Thanks for the PR! I have removed the section from README though. I thought it will be better to have documentation, if needed, in the TS file itself as JSDoc. It'd be great if you have time to put it there.

Thanks again!

**Pull request merged**
