### PR TITLE
fix: export GoogleSigninButtonDirective from its own module

### PR DESCRIPTION
**Pull request by hoi4**
to avoid errors when using the `GoogleSigninButtonDirective` in sub modules, it makes sense to export it from its own module. I also bumped the angular dependencies, otherwise installing the modules failed for me.

### CODE REVIEW

**Comment by hoi4** [comment]
This would be a breaking change :)

**Comment by hoi4** [comment]
Fixes #652 #647 #563

**Comment by Heatmanofurioso** [comment]
Hi @hoi4 Thanks for this!
The PR looks fine IMO.
Could you just bump the changelog, and the readme regarding this?

Especially on it being a breaking change in the changelog.

**Comment by hoi4** [comment]
Thanks for handling this so quickly! @Heatmanofurioso 🙏🏻

**Comment by Heatmanofurioso** [comment]
Thanks for the prompt help once again.
Will release V2 tomorrow once I'm back home. Currently traveling

**Comment by ikbalKalaycioglu** [comment]
I faced the same error and I found the solution by changing the version of the package.
1 ) Go to package.json
2 ) write the version like this
3 ) type Console npm install

that is all

```
"dependencies": {
    "@abacritt/angularx-social-login": "^**1.2.5**"
}
```

**Comment by nataly9a** [comment]
Hi, I installed update v.2.0.0, but asl-google-signin-button is not working for me

```
<asl-google-signin-button type="standard" size="medium" logo_alignment="center"
                                          (click)="signInWithGoogle()"></asl-google-signin-button>
```

in console I got next errors:


```
Unchecked runtime.lastError: The message port closed before a response was received.
polyfills.1fc71396c325abf2.js:1  
```        

`GET https://accounts.google.com/gsi/status?client_id=769563792794-tkttklnmndhgm3faph5e8qp2g5n00fll.apps.googleusercontent.com&as=kTNUTU5A1UN6%2F0RLb0ToRQ 403`

`[GSI_LOGGER]: The given origin is not allowed for the given client ID.`

`button:1          Failed to load resource: the server responded with a status of 403 ()`

**Comment by hoi4** [comment]
@nataly9a Seems like you did not configure the authorized origin correctly. Maybe this can help you: https://developers.google.com/identity/gsi/web/guides/get-google-api-clientid#get_your_google_api_client_id

**Comment by nataly9a** [comment]
@hoi4 I've got strange solution: I added my site with "www." to existing list of domains, and that's all - it works)). But 2 weeks ago all worked without it.

**Pull request merged**
