### PR TITLE
Microsoft Provider Cleanup and Detailed Documentation

### PR DESCRIPTION
**Pull request by jonstelly**
Fixes missing `user.authToken` that I had forgot to set for the Microsoft Provider in #338

### CODE REVIEW

**Comment by jonstelly** [comment]
@jaibatrik I added some documentation for the Microsoft Login Provider.  Take a look and let me know if that's helpful and where you'd like it.  Some things to get you to check:

- All of the init options for the MicrosoftProvider are optional.  The only thing needed is the clientId, the provider should use reasonable defaults.
- I added a `logout_redirect_uri` configuration option and tried to document the logic for how the logout_redirect_uri gets set during logout.  Does the way I document it make sense?
- I have to stop `ng serve` and run `ng build lib && ng serve` any time I make a library change and want to test in the demo app, so I added the `ng build lib` command to the demo app steps
- I also added a `Providers` section to the README that links to the Microsoft Provider specific documentation.  It felt like adding the Microsoft-specific documentation to the base README might be a bit too much, especially if we add documentation for other providers
- I notice there's a copy of `README.md` in `projects/lib` that seems like an exact copy of the root `README.md`.  I'm sure this is for getting the documentation to show up on npmjs.  Just a note that since I use a relative link to my new `microsoft-provider.md` file and it's at the root, if you copy `README.md` from the root into `projects/lib` it'll have a broken link.  I'm not sure what the build process is for this library but we could probably add a `.gitignore` for `projects/lib/*.md` and in the build script just `cp *.md ./projects/lib` so all documentation would show up in npmjs (I think?)

**Comment by jonstelly** [comment]
One other note, if you're seeing the demo app URL without the slash, check your console and I bet you'll see some errors on google and facebook initialization.  I was seeing those because I believe the google and facebook app registrations used for the demo app have their URLs with the trailing slash.

When I see those errors, it seems that will prevent the normal initialization of the library where a user session is silently resumed, even if it was a different provider.  If I comment out the Google and Facebook providers from the demo app then resuming the session on refresh works as expected.

**Review by jaibatrik — APPROVED** [review]
Thank you for the contribution.

**Comment by jaibatrik** [comment]
I'll push this to npm soon, hopefully this week itself.

**Pull request merged**
