### PR TITLE
fix issue 201 modify response when using offline access for google login

### PR DESCRIPTION
**Pull request by khelmar**

### CODE REVIEW

**Comment by jaibatrik** [comment]
Need to test with this fix.

**Comment by mustansirali** [comment]
I am also experiencing the same issue with offline access. This fix would be very helpful

**Comment by jaibatrik** [comment]
Hi, the description of the PR does not describe the problem in detail. Could anyone please update that? I have tested the code and it appears to work well, but I wanted to understand the problem before merging it.

**Comment by khelmar** [comment]
would the following work:

"fix issue 201 modify response when using offline access for google login to resolve Uncaught (in promise): TypeError: Cannot read property 'access_token' of null TypeError: Cannot read property 'access_token' of null at angularx-social-login"

**Comment by mustansirali** [comment]
have noticed that the initial oauth flow results in the aforementioned TypeError, but a subsequent attempt to authenticate works and returns an auth code. This auth code, however I am not able to  properly exchange for access/id tokens.

**Comment by khelmar** [comment]
> have noticed that the initial oauth flow results in the aforementioned TypeError, but a subsequent attempt to authenticate works and returns an auth code. This auth code, however I am not able to properly exchange for access/id tokens.

Are you getting a fully populated SocialUser?

**Comment by mustansirali** [comment]
> > have noticed that the initial oauth flow results in the aforementioned TypeError, but a subsequent attempt to authenticate works and returns an auth code. This auth code, however I am not able to properly exchange for access/id tokens.
> 
> Are you getting a fully populated SocialUser?

Yes. I fully populated SocialUser Object

**Comment by joaobosconff** [comment]
> have noticed that the initial oauth flow results in the aforementioned TypeError, but a subsequent attempt to authenticate works and returns an auth code. This auth code, however I am not able to properly exchange for access/id tokens.

have the same issue

**Comment by jaibatrik** [comment]
Need to resolve conflict.

**Comment by qqnc** [comment]
has the same issue? Is this fixed yet?

**Pull request merged**
