### PR TITLE
Add angular14 support

### PR DESCRIPTION
**Pull request by ranma42**
The library seems to work just fine on Angular 14, but the peer dependencies currently forbid it.
This branch updates the peer dependencies to support both 13.x and 14.x.

It is currently in draft because it relies on an alpha version of https://github.com/angular-eslint/angular-eslint/ (the 14.x version has not yet been released; according to https://github.com/angular-eslint/angular-eslint/pull/1004#issuecomment-1153620844 it should be released next weekend).

### CODE REVIEW

**Comment by alenosmanovic91x** [comment]
If you can not wait, like I couldn't go here
https://www.npmjs.com/package/@alenosmanovic91x/angularx-social-login-ws

**Comment by alenosmanovic91x** [comment]
@ranma42  if you are not in the position to wait ( like I was not ), I have published the same library with support of angular 14
https://www.npmjs.com/package/@alenosmanovic91x/angularx-social-login

**Comment by Heatmanofurioso** [comment]
Hey man.

I'm up to merging & deploying this PR.

Any reason for it to still be a draft?

**Comment by Heatmanofurioso** [comment]
Migrating this PR to https://github.com/abacritt/angularx-social-login/pull/516

Thank you @ranma42 for your help on this.
Really hope you don't mind me continuing it

**Pull request closed without merging**
