### PR TITLE
VKLoginProvider

### PR DESCRIPTION
**Pull request by petrovich2k**

### CODE REVIEW

**Comment by jaibatrik** [comment]
Fixes #325

**Review by jaibatrik — COMMENTED** [review]
This looks all good to me. Thanks for the PR!

One comment though - I see that you have added an entry in the `app/app.module.ts` with a dummy client id. I would not want to put a dummy id there, as the same app gets built and hosted as the demo site for the repository on merging of PRs.

If you are not comfortable creating a VK app, you can point me to the resources and I can create an app for the library.

Thanks again!

**Comment by petrovich2k** [comment]
@jaibatrik I have added a valid app_id for VK login provider. 
Do I need to add the information that VK is supported to the readme file?
Are there anything else that I need to change or add?

**Comment by jaibatrik** [comment]
Yeah, you could perhaps change the README to indicate that a VK login provider has been added.

**Comment by petrovich2k** [comment]
@jaibatrik I have added VKLoginProvider usage example to the README

**Comment by petrovich2k** [comment]
Also replaced the README in projects/lib with the README from the root folder
Mentioned VK in package.json

**Comment by petrovich2k** [comment]
@jaibatrik when are going to merge it? this weekend?

**Comment by trytocatcharg** [comment]
Do you know how to get the email of the user with this approach?

**Comment by petrovich2k** [comment]
@trytocatcharg I've spent a few hours on this, I reckon that vk doesn't disclosure user's email. I've tried to add the email scope identificator (4194304), but I only saw a confirmation that my email would be provided, I didn't get my email in the loginResponse parameter.

`  private signInInternal(resolve: any, reject: any) {
    VK.Auth.login((loginResponse: any) => {
      if (loginResponse.status === 'connected') {
        this.getUser(
          loginResponse.session.mid,
          loginResponse.session.sid,
          resolve
        );
      }
    }, '4194304');
  }`

**Comment by trytocatcharg** [comment]
This is what i did to get the email on my website (i know it´s not a perfect code, but its works for me).
I overrided the login method of VK javascript SDK just to add the redirect_uri as parameter (currenlty only accept cb and settings -the scope- and **they hardcoded the redirect url to 'blank.html'**).

```
function customLogin(cb, settings, redirect_uri) {
  if (!VK._apiId) {
    return false;
  }

  var url = VK._domain.main + '/' + VK._path.login + '?client_id='+VK._apiId+'&display=popup&redirect_uri='+ redirect_uri +'&response_type=token&openapi=1';
  if (settings && parseInt(settings, 10) > 0) {
    url += '&scope=' + settings;
  }
....
}

```

then i call my custom function instead of the VK.auth.login (i follow the same approach of your code)

```
  private signInInternal(resolve: any, reject: any) {
    customLogin((loginResponse: any) => {
      if (loginResponse.status === 'connected') {
        this.getUser(
          loginResponse.session.mid,
          loginResponse.session.sid,
          resolve
        );
      }
    }, this.VK_API_SCOPE, this.URL_REDIRECT);

    // VK.Auth.login((loginResponse: any) => {
    //   if (loginResponse.status === 'connected') {
    //     this.getUser(
    //       loginResponse.session.mid,
    //       loginResponse.session.sid,
    //       resolve
    //     );
    //   }
    // }, this.VK_API_SCOPE);
  }
```


With this, after the user login and authorize, VK redirect to my own page and in the querystring i get the email parameter.

**Comment by petrovich2k** [comment]
@trytocatcharg  I have done the same, e.g. added a custom implementation of VK.Auth.Login, etc., but instead of being redirected to the URL I have specified, I can see this page in a VK permission confirmation popup. I have pushed my solution in a separete branch. Could you take a look at the [pull-request](https://github.com/petrovich2k/angularx-social-login/pull/1)?

**Review by jaibatrik — APPROVED** [review]

**Comment by jaibatrik** [comment]
> 
> 
> @jaibatrik when are going to merge it? this weekend?

Hey sorry, I have been incredibly busy for some days. I'll push it to npm by tomorrow.

**Comment by jaibatrik** [comment]
The VK login provider is not working for me. The home page does not show user information after login. Not pushing to npm now.

**Comment by petrovich2k** [comment]
@jaibatrik it is working for me. I've commented all providers apart from the VK and run ng serve. See the [video](https://bit.ly/2Tpepbf). We can have a call on Skype to discuss this issue.

**Comment by petrovich2k** [comment]
@jaibatrik Skype, Facebook, whatever.
Skype: petrovich2k
FB: https://www.facebook.com/petukhoven

**Comment by trytocatcharg** [comment]
It's also working for me and I'm using 99% the same code

**Comment by jaibatrik** [comment]
My bad, it works for me in Chrome but not in Firefox. Can you check once from your end?

**Comment by petrovich2k** [comment]
@jaibatrik I've sorted this out. It happens due to the fact that new versions of Firefox block social media trackers. When I swithed it off in the browser's setings, the VK Login Provider started working for me.

**Comment by jaibatrik** [comment]
Sure, let me check and publish in that case.

**Comment by petrovich2k** [comment]
@jaibatrik Yesterday I reported the issue with Firefox to the support of VK. They replied that their developers are aware of the issue and the only way to fix it quickly is to turn off Enhanced Tracking Protection. That's what I did and recommended to you. They don't know how long the fix may take.

**Comment by jaibatrik** [comment]
Sure. I published it to npm for now.
Thanks!

**Pull request merged**
