### PR TITLE
Fixed issue 119

### PR DESCRIPTION
**Pull request by nicoprida**
https://github.com/abacritt/angularx-social-login/issues/119

### CODE REVIEW

**Comment by nicoprida** [comment]
If you decided accept this change, please don't forget generate a new version on npm

**Comment by bodinaren** [comment]
@nicoprida First of all, you'll need to undo the changes you did to the demo project.

And about your actual changes. Admittedly, I haven't tried your changes, but I fail to see what difference it makes if we initialize the social user inside our outside of the `/me` call. Facebook doesn't know the difference. Can you describe how the `appsecret_proof` is included in the `/me` call? I don't see any mention of it in the code.

**Comment by bodinaren** [comment]
As `resolve(user);` will never get called unless the `/me` function works your changes won't make a difference?

**Comment by nicoprida** [comment]
You need to understand that the main goal here its preserve `authToken `, if `me?` call don't work, the `authToken `will be null.
I don't worry about the `resolve`, because that method will fail if `appsecret_proof` is activated

**Comment by bodinaren** [comment]
That's my point. It's not preserved anywhere. Yes, you add it to a user object, but that user object is discarded when the `/me` call fails. You as a user of the library will never see this object.

**Comment by nicoprida** [comment]
I get your point but the first time I debug this code to see was what happens, the `user `object existed without any `me?` info, just the `authToken` was there. You can force an exception inside and see by yourself :)

test
This is the object that I was talking about

**Pull request closed without merging**
