### PR TITLE
#122 AuthServiceConfig can now also accept an observable

### PR DESCRIPTION
**Pull request by BrianWClausen**
I made it possible for AuthServiceConfig to accept an Observable as well as a provider list. This should resolve issue #122.

### CODE REVIEW

**Comment by jaibatrik** [comment]
@BrianWClausen Thank you very much for the contribution; this was such a long pending feature request. When you have time, would you mind adding the usage in the README as well?

**Comment by veteran1** [comment]
Hello, 
is there an exemple of this feature? 
Thanks

**Comment by jaibatrik** [comment]
In the newest version, it accepts a Promise instead of observable. In the current README, where we are providing the `SocialAuthServiceConfig`, you can provide a promise that resolves to `SocialAuthServiceConfig` there.

**Comment by veteran1** [comment]
Can you please provide an exemple? in app.module i tried this:
`
function appLoadFactory(authService: AuthService) {
  return () => authService.loadConfig().toPromise();
}
@NgModule({
...
providers: [
....
{
      provide:      'SocialAuthServiceConfig',
      useFactory:   appLoadFactory,
      deps:         [AuthService],
      multi:        true,
    }
]`

doesn't work for me

**Comment by jaibatrik** [comment]
What happens when you return promise instead of function? Like `function appLoadFactory(authService: AuthService) { return authService.loadConfig().toPromise(); }`.

**Comment by veteran1** [comment]
it was a typo in my code, it works now :)
I replaced return () => authService.loadConfig().toPromise(); by return authService.loadConfig().toPromise();

**Comment by Lorrhanl** [comment]
I'm trying to return an object like this in the function:

```
function factorySocialLogin() {
	return	{
		autoLogin: false,
		providers: [
			{
				id: FacebookLoginProvider.PROVIDER_ID,
				provider: new FacebookLoginProvider('...'),
			},
			{
				id: GoogleLoginProvider.PROVIDER_ID,
				provider: new GoogleLoginProvider('...'),
			}
		],
	} as SocialAuthServiceConfig;
}
```

in the provider I call it like this:
```
{
      provide: 'SocialAuthServiceConfig',
      useFactory: factorySocialLogin,
      multi: true
}
```

image


the object becomes an array within the function
image

then there is no config.providers
image

Am I doing something wrong? could help?

**Comment by jaibatrik** [comment]
Is the `multi: true` causing the provided value to be an array?

**Comment by sterichards** [comment]
Could an example be added please?

I don't see any changes to the readme that describe implementing this new feature

**Pull request merged**
