### PR TITLE
LinkedIn Provider

### PR DESCRIPTION
**Pull request by bleuscyther**
add Add LinkedIn provider and demo.
I created a LinkedIn APP just for the demo.

### CODE REVIEW

**Comment by jaibatrik** [comment]
@bleuscyther Thanks so much. Will check this once and merge it when I get some time.

**Comment by jaibatrik** [comment]
Hey @bleuscyther I am really sorry that I had to change the build system (based on https://github.com/filipesilva/angular-quickstart-lib) before I could review and merge your changes.

Would you be kind enough to pull the changes to your repository and make the changes and push back again? Else I can close this PR and manually make the changes you added.

**Comment by bleuscyther** [comment]
I  should have sometime during the week to resolve the merge issue.

**Comment by jaibatrik** [comment]
Thanks @bleuscyther!

**Comment by bleuscyther** [comment]
@jaibatrik all merge conflicts should be resolved now

**Comment by jaibatrik** [comment]
Thanks for the contribution! Will be releasing to npm shortly.

**Comment by arnabdatta** [comment]
Why settimeout was used in LinkedIn provider?

**Comment by piyush-ampersand** [comment]
@bleuscyther Can you please let me know how to get accessToken from linkedIn not the authToken as I need to send this accessToken a server where user is verified before registration ? TIA

**Comment by bleuscyther** [comment]
@arnabdatta it s a hack i used to make sure everything happens at the correct time. I did not have a clear understanding of why setTimeout fixed it at the time but now i can propose a cleaner version.

**Comment by bleuscyther** [comment]
@piyush-ampersand i think  i do that also , i dont trust the data from the user so i re-fetch the data on the server , you can use the Rest-API this time. 
https://developer.linkedin.com/docs/rest-api

**Comment by piyush-ampersand** [comment]
@bleuscyther I implemented rest-api but I think if I could get the accessToken on the client side that would be easier so just wanted to know if it is possible to get the accessToken when you are getting the other fields for linkedin service

**Pull request merged**
