### PR TITLE
added BaseLoginProvider to resolve a build issue

### PR DESCRIPTION
**Pull request by darkedges**
https://github.com/abacritt/angularx-social-login/issues/272

### CODE REVIEW

**Comment by jaibatrik** [comment]
Did this resolve your issue? Are you able to successfully create a provider after only this change?

**Comment by darkedges** [comment]
Sorry for the delay and apologies for the short description .

Yes this worked for me, it allowed me to develop my own provider which I am using @ https://signinwith.idaas.xyz

**Comment by jaibatrik** [comment]
@darkedges Hi, I am unable to resolve conflict on this, tried using both the command line options and the web editor in Github. If it's okay, could you please resolve the conflict / submit a new PR?

Thanks again for the PR!

**Comment by jaibatrik** [comment]
Changes merged now. Thanks again for the PR!

**Pull request closed without merging**
