### PR TITLE
Adding a parameter to use the GoogleApi.grantOfflineAccess() method …

### PR DESCRIPTION
**Pull request by OwlLaboratory**
…instead of GoogleApi.signIn()

### CODE REVIEW

**Comment by OwlLaboratory** [comment]
Hi ! :)

Any response about this PR ?

**Comment by jaibatrik** [comment]
Thanks for the PR. The changes look good to me. But I'll test it once before merging. Kindly use your own version of the library till then. Sorry about the inconvenience.

**Comment by OwlLaboratory** [comment]
Great ! Yes I use mine while waiting. Thanks for the response;)

**Comment by dgsqrs** [comment]
Just to be sure, does this modification enable the access_type=offline of the Google API ?

**Comment by OwlLaboratory** [comment]
Yes !

**Comment by dgsqrs** [comment]
@OwlLaboratory how can I use your fork with npm ? I got a badly formed package into my node_modules (demo folder, no src)

**Comment by dgsqrs** [comment]
@OwlLaboratory I try your PR from your repository but there is an issue. The authorization code is correctly returned but after that, you have to make a second api call to get the access & refresh token to be able to retrieve the user.

**Comment by webcat12345** [comment]
Can we use this feature?

**Comment by webcat12345** [comment]
to get refresh_token I send `prompt: consent` but it doesn't return `refresh_token` at all, any clue?

**Comment by OwlLaboratory** [comment]
@dgsqrs I'll see what you're talking about tomorrow !

@webcat12345 To get a "refresh_token", you have to do this operation at the server side. You need the Authorization code + your client_id and client_secret (https://developers.google.com/google-ads/scripts/docs/examples/generate-oauth20-refresh-token).

This PR retrieves the Authorization code of the user. When you activate offlineAccess, the authorization is returned if the user logs in with their Google Account. The second step is sending this code to my server to generate the refresh token and save it to the database for later.

**Comment by webcat12345** [comment]
@OwlLaboratory that flow works , thanks for clarification

**Comment by OwlLaboratory** [comment]
@dgsqrs Can you give me some additional information on your issue ? The refresh token must be generated at the server side. The access token is present in the response, I have checked !

**Comment by OwlLaboratory** [comment]
@jaibatrik Some news about the integration of this PR ?

**Pull request merged**
