### PR TITLE
Migrate to the new Google Identity Services library

### LINKED ISSUE #442: We should Migrate to the new Google Identity Services library
Yeah, they keep yelling, bla bla .... but we have time to 2023.
> [Action Required] Migrate to the new Google Identity Services library as soon as possible
> Hello Google Developer,
> 
> As announced earlier this month, the legacy Google Sign-In web solution will no longer be supported after March 31, 2023
> 

image
https://developers.google.com/identity/gsi/web/guides/migration

### PR DESCRIPTION
**Pull request by Jonnyprof**
- Change google endpoint
- Change entity to load
- Minor eslint fixes

closes #442 

PS: Please test it!

### CODE REVIEW

**Comment by rafa-as** [comment]
@jaibatrik can you check this PR please?

**Comment by mandziukvlad** [comment]
No need to test it.

_apis.google.com/js/platform.js_ 
_apis.google.com/js/client.js_
are modules of **Google API Client Library aka gapi.client** (_apis.google.com/js/api.js_) which is already being used and they are **not a part** of Google Identity Services.

You can read how to migrate to a new library [here](https://developers.google.com/identity/gsi/web/guides/migration)
Or if you want to see how to use it [go here](https://developers.google.com/identity/gsi/web/guides/migration#popup-mode_1)

**Comment by Jonnyprof** [comment]
Yes, I've followed the migration guide and the example from Google API Client Library for JavaScript (https://github.com/google/google-api-javascript-client/blob/master/docs/samples.md#authorizing-and-making-authorized-requests)

**Comment by smotornyuk** [comment]
Probably, you've used outdated guid. Look at [this line](https://github.com/abacritt/angularx-social-login/pull/473/files#diff-bbbef2dbf0187913045582b7cd75131a86cabfef5bd37134e4deb88d511eae87R23). 
You are using the old library from apis.google.com. [Here you can find an example explicitly stating that it's an "old style"](https://developers.google.com/identity/gsi/web/guides/migration#the_old_way)

[In the new style](https://developers.google.com/identity/gsi/web/guides/migration#the_new_way) you should use accounts.google.com

**Comment by Julien57970** [comment]
Can someone fix it and merge the PR plz ? Because we need to migrate before the 31st of March, I just receive a mail from Google about it.
"Our [announced plan](https://notifications.google.com/g/p/AD-FnExWLPynHt0Lof8B8Wi-K5nE4w1Vb5Cfvof9O0V1kytK6KvS2Wi7Ytgukx0m7gNicRCQa8c3WobZ36CIHh0Soqh9P00EPtz_TmWbXtfsjIVDLJUNCKWNCe1nr2QooOqeXQ8PbqJflkkhvlnwCtQ) earlier this month stated that authorization support for the Google Sign-In JavaScript platform library will no longer be supported after March 31, 2023."

**Comment by hheexx** [comment]
@Julien57970 dude, you have whole year left ;)

**Comment by Julien57970** [comment]
@hheexx I know but you don't know my C.I.S.O., he's already on my back for this.

**Comment by jaibatrik** [comment]
This is now published in v4.1.0.

**Comment by Androbin** [comment]
https://developers.googleblog.com/2022/03/gis-jsweb-authz-migration.html
> If your web pages use the **`apis.google.com/js/api.js`** or `apis.google.com/js/client.js` JavaScript modules to load the Platform Library, **you are affected** and **need to update** your existing implementation to use the new Identity Services client library.

@jaibatrik Issue #442 is **not** resolved by this PR and needs to be reopened.

**Comment by jaibatrik** [comment]
I'd appreciate if someone sends a PR. I don't think I myself will get time. Let's use issue https://github.com/abacritt/angularx-social-login/issues/489 to track this.

**Pull request merged**
