### PR TITLE
Check document is defined

### PR DESCRIPTION
**Pull request by GNURub**

### CODE REVIEW

**Comment by EliotRaven** [comment]
image
image
image
still not working(((((((((((((((((((((((

**Comment by EliotRaven** [comment]
> Change looks good :)

are you sure what you update version for npm package?
I still get problem with this...

please fix this problem asap

**Comment by jaibatrik** [comment]
Oh. Did the change got missed in npm? Let me check and publish again.

**Comment by jaibatrik** [comment]
Published to npm with the changes. Get v2.2.1.

**Comment by EliotRaven** [comment]
> Published to npm with the changes. Get v2.2.1.

It looks like it works! Thanks, I'll test it a few days

**Pull request merged**
