### PR TITLE
using new google AUTHENTICATION libs

### PR DESCRIPTION
**Pull request by Jin-K**
this is just some work in progress, trying to make it work with the new Google Identity Services library:
https://developers.google.com/identity/oauth2/web/guides/overview

### CODE REVIEW

**Comment by ravitejabommakanti** [comment]
Any plans to merge the PR ? Please confirm.

**Comment by Heatmanofurioso** [comment]
@Jin-K Weren't you able to make an implementation without the button?

From my searches, I also haven't found a solution

**Review by Heatmanofurioso — APPROVED** [review]

**Comment by Jin-K** [comment]
> @Jin-K Weren't you able to make an implementation without the button?
> 
> From my searches, I also haven't found a solution

@Heatmanofurioso no I wasn't with the Identity lib, but I've been working on a personal project this weekend and I've been able to authenticate AND authorize via 1 single popup, I'm using angular-oauth2-oidc for that. So I don't use the new Google lib at all there, only angular-oauth2-oidc which calls the google oauth2 oidc endpoints.
This way I'm receiving the idToken + accessToken from 1 method call.

I'll push the repo very soon.

**Comment by Heatmanofurioso** [comment]
@Jin-K First off, thank you for all your help here, and sorry for not pitching in more, but I've been really stomped on other things recently.

I didn't quite get your last line in comment.
You'll try and push it onto this project as an alternative authentication method?

If that were so, we could merge this one so people have a functioning mechanism, and then add the other as an alternative, if you and the rest of the community agree with so.

**Pull request merged**
